### ISSUE TITLE
JEI width

### ISSUE THREAD

**Issue by drakray** [XVTEAM/FaithfulMods#6]
![2017-03-14_17 04 21](https://cloud.githubusercontent.com/assets/4303126/23922386/8425d0ca-08d8-11e7-88de-7b0cf5c9df1e.png)

JEI background GUI is not wide enough

**Comment by MarikCZ** [comment]
I going to check it. This pack have one very big mistake. Some textures are drawed for 1.10.2 but other on 1.11.2. So I think problem is here.

**Comment by drakray** [comment]
no problem, it's just a minor visual thing, not a crashy one.
and it's relatively easy/quick to fix, not like if you where to x32 every Chisel texture ever lol XD

**Comment by xMrVizzy** [comment]
Yes, it's version mismatch, because JEI update very often!

**Comment by MarikCZ** [comment]
So this is the reason, why i want to create new repository Faithful Mods 1.10.2. :D

**Comment by xMrVizzy** [comment]
This trouble with only JEI, i can't do because of one mod JEI another 1.10.2 version of pack!

**Comment by MarikCZ** [comment]
I don't understand you. You can't do new 1.10.2 repository? Or you can't fix @drakray problem?

**Comment by drakray** [comment]
this width problem is for 1.11.2, just to specify

**Comment by MarikCZ** [comment]
Hey Vizzy, I really don't understand your plans - can you divide this repository to 1.10.2 and 1.11.2 version? There are continually repeating problems on versions. :(

**Comment by xMrVizzy** [comment]
No, it's bug only with JEI! Other mods update not so often. I can't make another version for 1.10.2, will be only 1.11.2 version

**Comment by MarikCZ** [comment]
Oh, I understand. So, just make !JEI 1.10.2 addon for Faithful"! heh?
